app.py
from flask import Flask, render_template
from routes.profile import profile_bp

app = Flask(__name__)
app.register_blueprint(profile_bp)

@app.route('/')
def home():
    return render_template(
        'index.html'
    )

if __name__ == '__main__':
    app.run(debug=True)

routes/profile.py
from flask import Blueprint, render_template

profile_bp = Blueprint('profile', __name__, template_folder='templates')

def get_user_details():
    user_data = {
        "username": "dinaraguleia",
        "nome_completo": "Dina Raguleia",
        "email": "dina@exemplo.com",
        "bio": "A cachorrinha mais linda do mundo."
    }
    return user_data

@profile_bp.route('/profile')
def index():
    dados_usuario = get_user_details()
    return render_template('profile/index.html', user=dados_usuario)

templates/base.html
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href="https://bootswatch.com/5/minty/bootstrap.min.css" rel="stylesheet">
    
    <title>{% block title %}Meu Site{% endblock %}</title>
  </head>

  <nav class="navbar navbar-expand-lg bg-light position-relative" data-bs-theme="light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">SIGAB</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor03">
            <ul class="navbar-nav me-auto">
            <li class="nav-item">
                <a class="nav-link active" href="{{ url_for('profile.index') }}">perfil</a>
                <span class="visually-hidden">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">turmas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">boletim</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">professores</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">serviços</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">fazer matrícula</a>
                    <a class="dropdown-item" href="#">criar email</a>
                </div>
            </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-sm-2" type="search" placeholder="buscar">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">buscar</button>
            </form>
        </div>
    </div>
  </nav>

  <body>
    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}SIGAB{% endblock %}

{% block content %}

{% endblock %}

templates/profile/index.html
{% extends 'base.html' %}

{% block title %}SIGAB{% endblock %}

{% block content %}
    <head>
        <title>Perfil do Usuário</title>
    </head>
    <body>
        {% if user %}
            <div class="mb-3">
                <fieldset disabled="">
                    <label class="form-label" for="disabledInput">Nome</label>
                    <input class="form-control" id="disabledInput" type="text" placeholder="{{ user.nome_completo }}" disabled="">
                </fieldset>
            </div>
            <div class="mb-3">
                <fieldset disabled="">
                    <label class="form-label" for="disabledInput">Username</label>
                    <input class="form-control" id="disabledInput" type="text" placeholder="{{ user.username }}" disabled="">
                </fieldset>
            </div>
            <div class="mb-3">
                <fieldset disabled="">
                    <label class="form-label" for="disabledInput">E-mail</label>
                    <input class="form-control" id="disabledInput" type="text" placeholder="{{ user.email }}" disabled="">
                </fieldset>
            </div>
            <div class="mb-3">
                <fieldset disabled="">
                    <label class="form-label" for="disabledInput">Bio</label>
                    <input class="form-control" id="disabledInput" type="text" placeholder="{{ user.bio }}" disabled="">
                </fieldset>
            </div>
        {% else %}
            <p>Usuário não encontrado!</p>
        {% endif %}

    </body>
{% endblock %}